spring:
  datasource:
    url: ${DbUrl}
    username: ${DbUser}
    password: ${DbPass}
    hikari:
      max-lifetime: 28500
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
server:
  error:
    include-stacktrace: never